set nocompatible
execute pathogen#infect()
syntax enable

colorscheme solarized
set background=dark

set backspace=indent,eol,start
set spell
set history=50
set mouse=a

set ruler
set showcmd
set incsearch
set number

set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

set ignorecase

set splitbelow
set splitright

set encoding=utf-8
set fileencoding=utf-8
set noswapfile
set nobackup
set nowritebackup

set colorcolumn=80

au BufRead,BufNewFile *.md set filetype=markdown

" Don't use Ex mode, use Q for formatting
map Q gq

map <silent> <C-n> :NERDTreeToggle<CR>

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" Switch between panes more easily
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

if has("autocmd")
  filetype plugin indent on

  augroup vimrcEx
  au!
  autocmd FileType text setlocal textwidth=78
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif
  augroup END

else
  set autoindent		" always set autoindenting on
endif " has("autocmd")

if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

nnoremap ; :
