set nocompatible

execute pathogen#infect()

syntax enable

set backspace=indent,eol,start
set spell
set history=50
set mouse=a

set ruler
set incsearch
set number
set nrformats=

set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

set ignorecase

set splitbelow
set splitright

set encoding=utf-8
set fileencoding=utf-8
set noswapfile
set nobackup
set nowritebackup

set colorcolumn=110

au BufRead,BufNewFile *.md set filetype=markdown

" Disable accidentally entering Ex mode
map Q <Nop>

map <silent> <C-n> :NERDTreeToggle<CR>

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U without undoing what you typed before it.
" Still do not properly understand this mapping but feel like it helps me out.
inoremap <C-U> <C-G>u<C-U>

" Switch between panes more easily
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

if has("autocmd")
  filetype plugin indent on

  augroup vimrcEx
    autocmd!

    autocmd FileType text setlocal textwidth=80

    " When editing a file, always jump to last known cursor position.
    " Don't do it for commit messages or when the position is invalid.
    autocmd BufReadPost *
          \ if line("'\"") > 1 && line("'\"") <= line("$") |
          \   exe "normal! g`\"" |
          \ endif
  augroup END

else
  set autoindent " always set autoindenting on
endif

