# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="clean"

# Aliases
alias ohmyzsh="vim ~/.oh-my-zsh"

alias -g zfile='vim ~/.zshrc'
alias -g vfile='vim ~/.vimrc'
alias -g gfile='vim ~/.gitconfig'

alias be="bundle exec"

alias rake='noglob rake'

#git-duet config
export GIT_DUET_ROTATE_AUTHOR=1

export HOMEBREW_NO_AUTO_UPDATE=1

# chruby configuration
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Plugins
plugins=(zsh-syntax-highlighting)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### For qmake
export PATH="$(brew --prefix qt@5.5)/bin:$PATH"

source $ZSH/oh-my-zsh.sh
