Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="clean"

# Aliases
alias ohmyzsh="vim ~/.oh-my-zsh"

alias -g zfile='vim ~/.zshrc'
alias -g vfile='vim ~/.vimrc'
alias -g gfile='vim ~/.gitconfig'

alias be="bundle exec"

# chruby configuration
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

source $ZSH/oh-my-zsh.sh
source ./zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
